name: p2
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2-app
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: p2-nginx
    ports:
      - 80:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: p2-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
